### ISSUE TITLE
[Feature Request] Multiple items for meal planner days

### ISSUE THREAD

**Issue by goose-ws** [hay-kot/mealie#115] opened 2021-01-23 03:23 UTC
If I'm using two or three recipes for one day, I'm not able to add all of them to each day, only one. An option to be able to "Add a recipe" per day would be helpful.

Specific use case is - Dinner is spaghetti and meatballs with salad and garlic bread

There may be a recipe for the meatballs only, but I don't want to leave out in my plan the spaghetti/salad/garlic bread.

**Comment by kentora** [comment] 2021-01-23 06:06
This is a feature that have been brought up before - this is actually a duplicate of #20 
I think that issue actually have a better use case, since the one you're giving would be solved better with #32, so that "dinner" will still be one recipe (with ingredients referencing reusable recipes)

**Comment by hay-kot** [comment] 2021-01-24 20:45
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.

**Closed by hay-kot** 2021-01-24 20:45 UTC
