### ISSUE TITLE
"Copy icon" not working in "sign up links" on raspberry pi (armv7)

### ISSUE THREAD

**Issue by maguilara** [hay-kot/mealie#397] opened 2021-05-07 21:40 UTC
**Describe the bug**
The quick-copy icon in the sign-up links sections is not working, no content is shared to the clipboard.

**Steps To Reproduce**
Please be specific!
1. Go to settings -> manager users
2. click on "create link" and add link name and proceed to save it.
3. Click on the quick-copy icon of the newly generated link

**Expected behavior**
Copy link to clipboard

**Actual Behavior**
No content is copied to clipboard

**Device Information (please complete the following information):**
 - OS: win10 (client), raspberryos 32bit (server). edit. raspberry pi 4 8gb
 - Deployment: docker-compose
 - Browser: happened first in firefox, tested brave and same thing
 - Version: 0.4.3
docker-compose file:
```
version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 9925:80
    environment:
      DB_TYPE: sqlite
      TZ: ${TZ}
    volumes:
      - ${ROOT_DOCKER}/mealie:/app/data
```
TZ, ROOT_DOCKER are environment variable that you can find on the .env file

**Comment by hay-kot** [comment] 2021-05-07 21:42
Seems to be working for me. Could you open your browser console and see if there are any errors when you try to copy the link?

**Comment by maguilara** [comment] 2021-05-07 22:04
Brave output after clicking on copy icon:
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'writeText' of undefined
    at s.updateClipboard (TheSignUpTable.vue:171)
    at click (TheSignUpTable.vue?bdb2:8)
    at nt (vue.runtime.esm.js:1854)
    at s.n (vue.runtime.esm.js:2179)
    at nt (vue.runtime.esm.js:1854)
    at s.e.$emit (vue.runtime.esm.js:3888)
    at s.click (VBtn.ts:163)
    at nt (vue.runtime.esm.js:1854)
    at HTMLButtonElement.n (vue.runtime.esm.js:2179)
    at HTMLButtonElement.Qr.o._wrapper (vue.runtime.esm.js:6917)
```

On firefox, I can't seem to find any error after clicking it. I'm not expert debugging on the browser, so I may have missed something, so let me kow if I need to follow an special procedure.

**Comment by wengtad** [comment] 2021-05-08 01:14
It's working for me on Brave or Firefox using v0.4.3.

**Comment by maguilara** [comment] 2021-05-08 04:29
> 
> 
> It's working for me on Brave or Firefox using v0.4.3.

I can only think of a misconfiguration on my side... but I haven't done anything out of the ordinary, I posted my docker-compose file, fwiw. I just tested the quick copy on my fire hd 10 tablet (android 8 or 9), my lineageos 18.1 android cellphone (android 11) and it doesn't work either. So I can only blame it on my server (?), which is a raspberry pi.

**Comment by sephrat** [comment] 2021-05-10 11:22
I can't reproduce it either on Firefox 88 or Chrome 90 for Windows 10. It's supposed to work on any recent browser: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText#browser_compatibility 
I would blame your client rather than your server. Something on your computer is preventing your browser to write to your clipboard. Try in private mode without any extension activated.

**Comment by maguilara** [comment] 2021-05-10 23:23
I just spun up a container on my linux partition (x64) and the quick-copy works fine, and on the same browser (firefox) I tested the one hosted on my raspberry pi, no joy. For the sake of testing, I did the same on a chromium browser which has no addons/extensions installed, same result. So it's definitely related to my server. If anybody else with a raspberry pi can confirm this behaviour, would be great.

**Comment by wengtad** [comment] 2021-05-11 02:28
Maybe you could try clear browser with a hard reload? Not sure it will help or not.
I'm only tested on firefox and brave on desktop. Will try out using android 9 on my phone later.

**Comment by hay-kot** [comment] 2021-06-20 06:09
Closing since armv7 support has been dropped

**Closed by hay-kot** 2021-06-20 06:09 UTC
Labels: bug

**Comment by johan-lejdung** [comment] 2021-08-03 21:34
Why was armv7 support dropped?

**Comment by zierbeek** [comment] 2021-08-03 21:36
Arm/v7 Support

Mealie will no longer build in CI/CD due to a issue with the rust compiler on 32 bit devices. You can reference this issue on the matrix-org/synapse Github page that are facing a similar issue. You may still be able to build the docker image you-self.
https://github.com/matrix-org/synapse/issues/9403

https://hay-kot.github.io/mealie/changelog/v0.5.0/

**Comment by johan-lejdung** [comment] 2021-08-03 21:54
hmm okay, that's unfortunate. Raspberry Pi 64-bit is still in beta 😓
