### ISSUE TITLE
First-time docker run causes database error

### ISSUE THREAD

**Issue by FoxxMD** [hay-kot/mealie#98] opened 2021-01-19 15:50 UTC
on both the `latest` and `dev` tag: `docker run -d --name='mealie'  -v '/my/path/to/mealie':'/app/data':'rw' 'hkotel/mealie:latest'`

```
[2021-01-19 10:45:57 -0500] [11] [INFO] Worker exiting (pid: 11)
[2021-01-19 10:45:57 -0500] [12] [ERROR] Exception in worker process

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: table meal already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.8/site-packages/uvicorn/workers.py", line 63, in init_process
super(UvicornWorker, self).init_process()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
self.load_wsgi()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
mod = importlib.import_module(module)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/app/app.py", line 7, in <module>
from routes import (
File "/app/routes/backup_routes.py", line 6, in <module>
from services.backups.exports import backup_all
File "/app/services/backups/exports.py", line 7, in <module>
from services.meal_services import MealPlan
File "/app/services/meal_services.py", line 5, in <module>
from db.database import db
File "/app/db/database.py", line 1, in <module>
from db.db_mealplan import _Meals
File "/app/db/db_mealplan.py", line 6, in <module>
from db.db_setup import USE_MONGO, USE_SQL
File "/app/db/db_setup.py", line 9, in <module>
sql_global_init(SQLITE_FILE)
File "/app/db/sql/db_session.py", line 26, in globa_init
SqlAlchemyBase.metadata.create_all(engine)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4553, in create_all
bind._run_visitor(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
conn._run_visitor(visitorcallable, element, **kwargs)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 783, in visit_metadata
self.traverse_single(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
self.connection.execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
return connection._execute_ddl(self, multiparams, params)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
ret = self._execute_context(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
{"loglevel": "info", "workers": 40, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
self.dialect.do_execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table meal already exists
[SQL:
CREATE TABLE meal (
id INTEGER NOT NULL,
parent_id VARCHAR,
slug VARCHAR,
name VARCHAR,
date DATE,
"dateText" VARCHAR,
image VARCHAR,
description VARCHAR,
PRIMARY KEY (id),
FOREIGN KEY(parent_id) REFERENCES mealplan (uid)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

[2021-01-19 10:45:57 -0500] [12] [INFO] Worker exiting (pid: 12)
[2021-01-19 10:45:57 -0500] [35] [INFO] Booting worker with pid: 35
[2021-01-19 10:45:57 -0500] [9] [ERROR] Exception in worker process

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: table mealplan already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.8/site-packages/uvicorn/workers.py", line 63, in init_process
super(UvicornWorker, self).init_process()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
self.load_wsgi()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
mod = importlib.import_module(module)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/app/app.py", line 7, in <module>
from routes import (
File "/app/routes/backup_routes.py", line 6, in <module>
from services.backups.exports import backup_all
File "/app/services/backups/exports.py", line 7, in <module>
from services.meal_services import MealPlan
File "/app/services/meal_services.py", line 5, in <module>
from db.database import db
File "/app/db/database.py", line 1, in <module>
from db.db_mealplan import _Meals
File "/app/db/db_mealplan.py", line 6, in <module>
from db.db_setup import USE_MONGO, USE_SQL
File "/app/db/db_setup.py", line 9, in <module>
sql_global_init(SQLITE_FILE)
File "/app/db/sql/db_session.py", line 26, in globa_init
SqlAlchemyBase.metadata.create_all(engine)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4553, in create_all
bind._run_visitor(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
conn._run_visitor(visitorcallable, element, **kwargs)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 783, in visit_metadata
{"loglevel": "info", "workers": 40, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
self.traverse_single(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
self.connection.execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
return connection._execute_ddl(self, multiparams, params)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
ret = self._execute_context(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table mealplan already exists
[SQL:
CREATE TABLE mealplan (
uid INTEGER NOT NULL,
"startDate" DATE,
"endDate" DATE,
PRIMARY KEY (uid),
UNIQUE (uid)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

[2021-01-19 10:45:57 -0500] [9] [INFO] Worker exiting (pid: 9)
[2021-01-19 10:45:57 -0500] [14] [ERROR] Exception in worker process

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: table meal already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.8/site-packages/uvicorn/workers.py", line 63, in init_process
super(UvicornWorker, self).init_process()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
self.load_wsgi()
File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
mod = importlib.import_module(module)
File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 783, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/app/app.py", line 7, in <module>
from routes import (
File "/app/routes/backup_routes.py", line 6, in <module>
from services.backups.exports import backup_all
File "/app/services/backups/exports.py", line 7, in <module>
from services.meal_services import MealPlan
File "/app/services/meal_services.py", line 5, in <module>
from db.database import db
File "/app/db/database.py", line 1, in <module>
from db.db_mealplan import _Meals
File "/app/db/db_mealplan.py", line 6, in <module>
from db.db_setup import USE_MONGO, USE_SQL
File "/app/db/db_setup.py", line 9, in <module>
sql_global_init(SQLITE_FILE)
File "/app/db/sql/db_session.py", line 26, in globa_init
SqlAlchemyBase.metadata.create_all(engine)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4553, in create_all
bind._run_visitor(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
conn._run_visitor(visitorcallable, element, **kwargs)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 783, in visit_metadata
self.traverse_single(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
return meth(obj, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
self.connection.execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
return connection._execute_ddl(self, multiparams, params)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
ret = self._execute_context(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
self._handle_dbapi_exception(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
util.raise_(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
raise exception
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table meal already exists
[SQL:
CREATE TABLE meal (
id INTEGER NOT NULL,
parent_id VARCHAR,
slug VARCHAR,
name VARCHAR,
date DATE,
"dateText" VARCHAR,
{"loglevel": "info", "workers": 40, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
image VARCHAR,
description VARCHAR,
PRIMARY KEY (id),
FOREIGN KEY(parent_id) REFERENCES mealplan (uid)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

[2021-01-19 10:45:57 -0500] [14] [INFO] Worker exiting (pid: 14)
[2021-01-19 10:45:57 -0500] [36] [INFO] Booting worker with pid: 36
[2021-01-19 10:45:57 -0500] [37] [INFO] Booting worker with pid: 37
[2021-01-19 10:45:57 -0500] [38] [INFO] Booting worker with pid: 38
{"loglevel": "info", "workers": 40, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 202, in run
self.manage_workers()
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
self.spawn_workers()
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 617, in spawn_workers
time.sleep(0.1 * random.random())
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
self.reap_workers()
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/gunicorn", line 8, in <module>
sys.exit(run())
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 228, in run
super().run()
File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
Arbiter(self).run()
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
self.halt(reason=inst.reason, exit_status=inst.exit_status)
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
self.stop()
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
time.sleep(0.1)
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
self.reap_workers()
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 531, in reap_workers
if not worker:
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
self.reap_workers()
File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
raise HaltServer(reason, self.WORKER_BOOT_ERROR)
```

On the second attempt the container starts up correctly. I'm assuming there is an issue wtih the sql scripts executed when no db is found. Maybe a "CREATE IF NOT EXISTS" is missing somewhere?

**Comment by hay-kot** [comment] 2021-01-19 17:30
I did notice this issue on my Pi. I wasnt able to replicate it on my main machine. Are you using ARM by chance?

**Comment by FoxxMD** [comment] 2021-01-19 17:38
I'm using `amd64`. It only happens if the data volume is completely new, I would guess.

**Comment by hay-kot** [comment] 2021-01-19 18:36
> 
> 
> I'm using `amd64`. It only happens if the data volume is completely new, I would guess.

Odd...I'll look into it and see if I can figure out what's going on. Thanks!

**Comment by brasilikum** [comment] 2021-01-20 17:58
I confirmed this on my m1 MacBook.

As a workaround: add `—platform linux/amd64`

**Comment by hay-kot** [comment] 2021-01-20 18:01
This *may* be fixed in the new container configuration that I'm developing. I didn't get the same error. You can try the [Alpine image](https://hub.docker.com/layers/hkotel/mealie/alpine/images/sha256-9d13e6395ef8f0cf91c61687a8af83e1f9c16cf0701fca38c0e527cc17d15fb5?context=repo) on dockerhub. Although it should be noted that the alpine version is currently in development and shouldn't be used as your primary install, just for testing. It also only supports SQLite.

**Comment by nickcj931** [comment] 2021-01-21 09:06
Was getting the same issue when I was testing the unraid template last night. 

To confirm using **hkotel/mealie:alpine** image fixes the first time run problem, and i didnt have any issues on first run once I switched image.

I am going to delay my pull request to get the unraid template live as this will throw loads of problems for users. #37

**Comment by FoxxMD** [comment] 2021-01-21 13:38
@nickcj931 haha didn't realize I was behind the times!. I've got a template sitting [in my repo](https://github.com/FoxxMD/unraid-docker-templates) (locally) and was waiting for this to be resolved before pushing it out.

**Comment by nickcj931** [comment] 2021-01-21 13:54
@FoxxMD haha sorry didnt realise anyone picked it up when i spoke with hay-kot, You may as well add it into your own repo saves doing another pull on selfhosters/unRAID-CA-templates since you have your own CA repo published 😄 (How does one get their own repo into CA by the way??)

**Comment by FoxxMD** [comment] 2021-01-21 15:35
@nickcj931 Nah you should go ahead and and re-open the PR. Sorry this is getting off-topic hay-kot :sweat_smile: 

I started my repo long before selfhosters but their approach is better for this use-case, IMO. 

My opinion on repos now is that a solo repo (like mine) is good when I (the template author) am also the author of the docker image and preferably the code for the project the docker image is for -- because in that instance the author can sync changes vertically across all development and has an incentive to keep everything maintained since it's all their work. Additionally have to stay active on the support thread in the unraid forums.

Otherwise I believe a community repo like selfhosters is a better alternative since it takes the responsibility off of a single user from maintaining a one-off template for a docker image and project code they don't own (and don't have incentive to keep maintained) and gives that responsibility back to the community.

As for getting your own repo in to CA, need to message [Squid](https://forums.unraid.net/profile/10290-squid/) on the forums with the url (and I assume at least one working repo) and he adds it.

**Comment by hay-kot** [comment] 2021-01-21 16:01
FYI. The alpine container tag was simply for build testing and is likely not stable and will be removed at some point when it's changes are rolled into the main branch. Thanks for working on the unraid stuff!

**Comment by alex-phillips** [comment] 2021-01-28 22:26
Any update on this? the :latest tag container currently has this issue, no new install can be spun up it seems.

**Comment by hay-kot** [comment] 2021-01-28 22:45
> Any update on this? the :latest tag container currently has this issue, no new install can be spun up it seems.

Currently I've been able to work around it. By rerunning the container command. I'm working on a new project at work and my time is very limited for the next week or so. It has been fixed in the dev branch. My guess is that it is a problem with the Gunivorn server workings trying to create the database, so switching the docker file to use A single Uvicorn instance may resolve the issue.

Hopefully someone can jump in and submit a PR while I'm unable to work on it.

**Comment by alex-phillips** [comment] 2021-01-28 23:00
I'd be happy to issue a PR, but not sure where those workers are defined.

**Comment by hay-kot** [comment] 2021-01-28 23:09
> I'd be happy to issue a PR, but not sure where those workers are defined.

That would be awesome! It's defined in the dockerfile. Currently it uses the Docker file base provided by the FastAPI developer and uses the Gunivorn server to run the workers. You may only need to change the run command and rebuilt the container for it to run correctly. 

https://fastapi.tiangolo.com/deployment/docker/

Those docs may be helpful.

**Comment by alex-phillips** [comment] 2021-01-28 23:29
@hay-kot It looks like the issue is when the settings are initially running, specifically setting up the scheduler (might be a problem in other areas), every worker is attempting to do this setup so the run fails because of duplicate database entry attempts. I would suggest this code gets pulled out into a pre-run setup and not have it part of the actual app runtime - that is, if you want this to be a scalable microservice.

Otherwise, adding the environment variable `MAX_WORKERS=1` to the docker run command / compose file fixes the issue without any code changes or docker builds.

**Comment by hay-kot** [comment] 2021-01-29 00:12
@alex-phillips Splitting those up is in my list for the next release. I haven't dug into it much, but the current code is a bit of a mess. For the time being setting the max working to 1 is probably the best solution until I can break up those "services"

**Closed** 2021-02-08 18:47 UTC
Labels: fixed pending release
