### ISSUE TITLE
There is no edit button for the notifications

### ISSUE THREAD

**Issue by ltctceplrm** [hay-kot/mealie#539] opened 2021-06-17 13:27 UTC
**Describe the bug**
Not really a bug but maybe an oversight? After adding a notification you can press delete or test but you can't edit the apprise URL or the Subscribed Events.

**Steps To Reproduce**
Please be specific!
1. I added a notification for discord
2. Saved it
3. No way to edit it

**Expected behavior**
An edit button or some way to edit the notification

**Actual Behavior**
No way to edit the notification

**Device Information (please complete the following information):**
 - OS: [Debian]
 - Deployment: [docker-compose]
 - Browser: [Firefox or chrome]
 - Version: [v0.50]

**Comment by hay-kot** [comment] 2021-06-17 15:13
This is by design. Since the information provided contains secrets (api keys), I was treating them as passwords so they are not viewable/editable. From the UI. 

If others want this feature as well, I can look into adding it.

**Comment by zierbeek** [comment] 2021-06-17 15:14
I think this is the right approach. Some other services do it the same way.

**Comment by ltctceplrm** [comment] 2021-06-17 20:14
That makes a lot of sense, I hadn't thought about it like that. It's not that hard to set up the webhooks again so I don't necessarily need an edit button, do I mark this issue as closed?
It could be useful to just be able to edit on which occasions the notifications get sent, that way you still keep the api keys secret.

**Comment by TheZoker** [comment] 2021-07-23 16:53
What about only allowing the user to edit the notification channels? I setup a notification and later noticed, that I don't want a notification when mealie creates a backup. But instead of just editing the notification I had to delete it and re-add it (looking up my secret again). 
So how about an edit button, that only allows to change notification channels, but does not display or allow to edit the provided tokens?

**Comment by hay-kot** [comment] 2022-01-10 02:06
This will now be fixed in v1. Each group will now have their own setup for Apprise-based notifications. You'll be able to update the Apprise URL without it being available on the frontend, as well as change the event types you're subscribed to. 

![image](https://user-images.githubusercontent.com/64056131/148710772-c8d6e187-a3d3-4251-bae0-ba8dbc91a486.png)

**Closed** 2022-05-24 16:45 UTC
Labels: bug, fixed in v1
