### ISSUE TITLE
Internal error when adding URL

### ISSUE THREAD

**Issue by engelkek** [hay-kot/mealie#28] opened 2021-01-04 15:15 UTC
When adding a random recipe URL (https://www.chefkoch.de/rezepte/2235331358009600/Pizza-Knoblauch-Champignon-Paprika-vegan.html) this error occurs:

```
mealie           | INFO:     172.18.0.1:56506 - "POST /api/recipe/create-url/ HTTP/1.1" 500 Internal Server Error
mealie           | ERROR:    Exception in ASGI application
mealie           | Traceback (most recent call last):
mealie           |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
mealie           |     result = await app(self.scope, self.receive, self.send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
mealie           |     return await self.app(scope, receive, send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
mealie           |     await super().__call__(scope, receive, send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
mealie           |     await self.middleware_stack(scope, receive, send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
mealie           |     raise exc from None
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
mealie           |     await self.app(scope, receive, _send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
mealie           |     raise exc from None
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
mealie           |     await self.app(scope, receive, sender)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
mealie           |     await route.handle(scope, receive, send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
mealie           |     await self.app(scope, receive, send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
mealie           |     response = await func(request)
mealie           |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
mealie           |     raw_response = await run_endpoint_function(
mealie           |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
mealie           |     return await dependant.call(**values)
mealie           |   File "./routes/recipe_routes.py", line 45, in get_recipe_url
mealie           |     slug = create_from_url(url)
mealie           |   File "./services/scrape_services.py", line 29, in create_from_url
mealie           |     recipe = Recipe(**recipe_data)
mealie           |   File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
mealie           | pydantic.error_wrappers.ValidationError: 1 validation error for Recipe
mealie           | recipeInstructions
mealie           |   value is not a valid list (type=type_error.list)
```

I started Mealie using the Docker Compose file from the docs.

**Comment by hay-kot** [comment] 2021-01-05 01:33
Closing as a Duplicate of Issue #7 . We've got some people on the discord working on improving the parser. Thanks!

**Closed by hay-kot** 2021-01-05 01:33 UTC
