### ISSUE TITLE
[Browser Compatibility] WebP Images not supported in Safari below 14.4 (Duplicate)

### ISSUE THREAD

**Issue by BenJordan23** [hay-kot/mealie#659] opened 2021-08-27 21:34 UTC
**Describe the bug**

All recipes are not shown on the iPad. Only when I press the random button, a random recipe appears.

**Expected behavior**
Recipes should appear in recent and all recipes window

**Actual Behavior**
All recipes window and homepage are empty when viewed on iPad. iPhone and Mac Browser have no issues.

**Device Information:**
 - OS: iOS
 - Deployment: Docker-version
 - Browser: safari
 - Version: 0.5.2

**Comment by hay-kot** [comment] 2021-08-30 19:12
1. What version of ios and safari are you running? 
2. Does it work if you use chrome on the Ipad?

**Comment by BenJordan23** [comment] 2021-09-02 07:04
Hi, 

1. I run iOS 14.7.1 on the iPad
2. Mealie recipes are displayed correctly with the Brave (Chrome) Browser on the same iPad.

I have checked another iPad and iPhones and they display the recipes correctly (on chrome and safari).

Many thanks and best regards,
Benjamin

**Comment by alucarddelta** [comment] 2021-09-12 00:46
> Hi, 1. I run iOS 14.7.1 on the iPad 2. Mealie recipes are displayed correctly with the Brave (Chrome) Browser on the same iPad. I have checked another iPad and iPhones and they display the recipes correctly (on chrome and safari). Many thanks and best regards, Benjamin

I only just started using this app, so my recipe count is quite low (10ish), But I'm not seeing any issues using safari on my Ipad.
I am using a different Ipad model however, Air 4th Gen. 

Could it be the screen Resolution is causing a rendering issue in safari? (only real difference I can think of)...
- Ipad 2 - 768x1028
- Ipad air 4 - 2360 x 1640

------------------------------

- OS: 14.7.1
- Type: Ipad Air 4th gen
- Deployment: Docker-version, Unraid
- Browser: safari
- Version: 0.5.2

**Comment by hay-kot** [comment] 2021-09-12 01:16
I'm betting it's Safari's Webp Support

See https://caniuse.com/webp

**Comment by hay-kot** [comment] 2021-09-20 22:28
Duplicate of #616

**Closed by hay-kot** 2021-09-20 22:28 UTC
Labels: bug
